create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key,
  email text not null unique,
  created_at timestamptz not null default now(),
  constraint profiles_email_format check (email = lower(email) and position('@' in email) > 1)
);

create table if not exists public.restaurants (
  id bigint generated by default as identity primary key,
  name text not null unique,
  area text not null,
  cuisine text not null,
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  description text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.dishes (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  name text not null,
  price numeric(7, 2) not null check (price >= 0),
  description text not null default '',
  course text not null default 'mains' check (course in ('starters', 'mains', 'desserts', 'drinks')),
  menu_position integer not null default 0 check (menu_position >= 0),
  diets text[] not null default '{}',
  allergens text[] not null default '{}',
  crowd_tags jsonb not null default '{}',
  sponsored boolean not null default false,
  created_at timestamptz not null default now(),
  unique (restaurant_id, name)
);

-- The Plate prototype may already have the original flat dishes table. These
-- additions preserve its rows while moving restaurant and menu data into the
-- relational shape used by the application.
alter table public.dishes add column if not exists restaurant_id bigint references public.restaurants(id) on delete cascade;
alter table public.dishes add column if not exists description text not null default '';
alter table public.dishes add column if not exists course text not null default 'mains';
alter table public.dishes add column if not exists menu_position integer not null default 0;
alter table public.dishes add column if not exists diets text[] not null default '{}';
alter table public.dishes add column if not exists allergens text[] not null default '{}';
alter table public.dishes add column if not exists crowd_tags jsonb not null default '{}';
alter table public.dishes add column if not exists sponsored boolean not null default false;
alter table public.dishes add column if not exists created_at timestamptz not null default now();

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'dishes' and column_name = 'restaurant'
  ) then
    alter table public.dishes alter column restaurant drop not null;
    alter table public.dishes alter column area drop not null;
    alter table public.dishes alter column cuisine drop not null;
  end if;
end $$;

create table if not exists public.ratings (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  dish_id bigint not null references public.dishes(id) on delete cascade,
  score numeric(3, 1) not null check (score between 0 and 10),
  tags text[] not null default '{}',
  comment text not null default '' check (char_length(comment) <= 2000),
  visited_at date not null default current_date check (visited_at <= current_date),
  created_at timestamptz not null default now(),
  constraint ratings_tags_limit check (cardinality(tags) <= 8)
);

alter table public.ratings alter column score type numeric(3, 1) using score::numeric;
alter table public.ratings add column if not exists tags text[] not null default '{}';
alter table public.ratings add column if not exists comment text not null default '';
alter table public.ratings add column if not exists visited_at date not null default current_date;
alter table public.ratings add column if not exists created_at timestamptz not null default now();
alter table public.ratings drop constraint if exists ratings_dish_id_user_id_key;
alter table public.ratings drop constraint if exists ratings_user_id_fkey;
alter table public.ratings drop constraint if exists ratings_tags_check;

update public.ratings
set visited_at = created_at::date
where visited_at is null;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'ratings_score_range') then
    alter table public.ratings add constraint ratings_score_range check (score between 0 and 10);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'ratings_comment_length') then
    alter table public.ratings add constraint ratings_comment_length check (char_length(comment) <= 2000);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'ratings_visited_not_future') then
    alter table public.ratings add constraint ratings_visited_not_future check (visited_at <= current_date);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'ratings_tags_limit') then
    alter table public.ratings add constraint ratings_tags_limit check (cardinality(tags) <= 8);
  end if;
end $$;

create table if not exists public.rating_photos (
  id uuid primary key default gen_random_uuid(),
  rating_id uuid not null references public.ratings(id) on delete cascade,
  user_id uuid not null,
  storage_path text not null unique,
  mime_type text not null check (mime_type in ('image/jpeg', 'image/png', 'image/webp')),
  size_bytes integer not null check (size_bytes > 0 and size_bytes <= 5242880),
  created_at timestamptz not null default now()
);

create index if not exists dishes_restaurant_menu_idx
  on public.dishes (restaurant_id, course, menu_position);
create index if not exists ratings_dish_idx on public.ratings (dish_id);
create index if not exists ratings_user_visit_idx on public.ratings (user_id, visited_at desc);
create index if not exists rating_photos_rating_idx on public.rating_photos (rating_id);

insert into public.restaurants (id, name, area, cuisine, latitude, longitude, description)
values
  (1, 'Najar''s Place', 'St Giles''', 'Lebanese', 51.75503, -1.26055, 'A tiny St Giles'' favourite for generous wraps, sharp pickles and queues that move quickly.'),
  (2, 'Oli''s Thai', 'Iffley Road', 'Thai', 51.74296, -1.23861, 'A much-loved neighbourhood dining room serving deeply flavoured, carefully balanced Thai food.'),
  (3, 'Spiced Roots', 'Cowley Road', 'Caribbean', 51.74892, -1.24118, 'Caribbean cooking with slow braises, bright spice and a warm Cowley Road welcome.'),
  (4, 'The Coconut Tree', 'George Street', 'Sri Lankan', 51.75336, -1.26219, 'Sri Lankan small plates made for sharing, from fiery fried bites to crisp-edged hoppers.'),
  (5, 'Pierre Victoire', 'Little Clarendon St', 'French', 51.75840, -1.26150, 'Relaxed French bistro cooking in the heart of Jericho.'),
  (6, 'G&D''s Cafe', 'St Aldate''s', 'Cafe', 51.75065, -1.25698, 'An independent Oxford institution for bagels, coffee and house-made ice cream.'),
  (7, 'Sasi''s Thai', 'Gloucester Green', 'Thai', 51.75378, -1.26309, 'A market favourite known for comforting rice dishes and fast, friendly lunches.'),
  (8, 'Taberu', 'Cowley Road', 'Japanese', 51.74813, -1.23969, 'Casual Japanese comfort food, crisp katsu and generous bowls on Cowley Road.'),
  (9, 'Branca', 'Walton Street', 'Italian', 51.76017, -1.26609, 'A lively Jericho brasserie with Italian-inspired plates and a bright neighbourhood feel.')
on conflict (id) do update set
  name = excluded.name,
  area = excluded.area,
  cuisine = excluded.cuisine,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  description = excluded.description;

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'dishes' and column_name = 'restaurant'
  ) then
    execute $legacy_restaurants$
      insert into public.restaurants (name, area, cuisine, latitude, longitude, description)
      select distinct
        legacy.restaurant,
        coalesce(nullif(legacy.area, ''), 'Oxford'),
        coalesce(nullif(legacy.cuisine, ''), 'Restaurant'),
        51.7528,
        -1.2528,
        'An Oxford restaurant carried forward from the original Plate catalogue.'
      from public.dishes legacy
      where nullif(legacy.restaurant, '') is not null
        and not exists (
          select 1 from public.restaurants current_restaurant
          where lower(current_restaurant.name) = lower(legacy.restaurant)
        )
      on conflict (name) do nothing
    $legacy_restaurants$;

    if exists (
      select 1 from information_schema.columns
      where table_schema = 'public' and table_name = 'dishes' and column_name = 'tag_counts'
    ) then
      execute $legacy_dishes$
        update public.dishes legacy
        set restaurant_id = restaurant.id,
            crowd_tags = case
              when legacy.crowd_tags = '{}'::jsonb then coalesce(legacy.tag_counts, '{}'::jsonb)
              else legacy.crowd_tags
            end
        from public.restaurants restaurant
        where legacy.restaurant_id is null
          and lower(restaurant.name) = lower(legacy.restaurant)
      $legacy_dishes$;
    else
      execute $legacy_dishes$
        update public.dishes legacy
        set restaurant_id = restaurant.id
        from public.restaurants restaurant
        where legacy.restaurant_id is null
          and lower(restaurant.name) = lower(legacy.restaurant)
      $legacy_dishes$;
    end if;
  end if;
end $$;

insert into public.dishes (
  id, restaurant_id, name, price, description, course, menu_position,
  diets, allergens, crowd_tags, sponsored
)
values
  (1, 1, 'Falafel Wrap', 5.50, 'Hand-rolled falafel, pickled turnip, tahini and chilli in warm flatbread. The queue exists for a reason.', 'mains', 1, array['Vegetarian', 'Vegan'], array['Gluten', 'Sesame'], '{"Would order again":162,"Great value":149,"Fresh":96,"Crispy":54}'::jsonb, false),
  (2, 1, 'Halloumi & Za''atar Wrap', 6.00, 'Grilled halloumi dusted with za''atar, tomato, mint and garlic sauce.', 'mains', 2, array['Vegetarian'], array['Gluten', 'Dairy', 'Sesame'], '{"Comforting":84,"Great value":77,"Would order again":71,"Salty":45}'::jsonb, false),
  (3, 2, 'Aubergine Massaman', 14.50, 'Slow-cooked aubergine in a deep massaman curry with peanuts and jasmine rice. Book weeks ahead - worth it.', 'mains', 1, array['Vegetarian', 'Vegan'], array['Nuts'], '{"Rich":121,"Would order again":118,"Comforting":88,"Sweet":72,"Spicy":66}'::jsonb, false),
  (4, 2, 'Pad Krapow Chicken', 13.00, 'Holy basil stir-fry with a crispy fried egg. Properly hot - ask for medium if unsure.', 'mains', 2, '{}', array['Soy', 'Egg'], '{"Spicy":97,"Fresh":64,"Would order again":59,"Savoury":51}'::jsonb, false),
  (5, 3, 'Jerk Chicken', 16.00, 'Charred jerk chicken with rice and peas and scotch bonnet heat that builds slowly.', 'mains', 1, '{}', '{}', '{"Spicy":78,"Generous portion":66,"Would order again":58,"Smoky":46}'::jsonb, false),
  (6, 3, 'Curried Goat', 17.50, 'Slow-braised goat, falling off the bone, with plantain and coconut rice.', 'mains', 2, '{}', '{}', '{"Rich":71,"Comforting":55,"Generous portion":49,"Saucy":35}'::jsonb, false),
  (7, 4, 'Hot Battered Cuttlefish', 8.50, 'Crisp-fried cuttlefish tossed in fiery Sri Lankan spice. Made for sharing, rarely shared.', 'starters', 1, '{}', array['Shellfish', 'Gluten'], '{"Crispy":63,"Spicy":51,"Would order again":40,"Sweet":32}'::jsonb, false),
  (8, 4, 'Dhal & Pol Sambol Hopper', 7.00, 'Lacy coconut hopper with creamy dhal and fresh coconut sambol.', 'mains', 1, array['Vegetarian', 'Vegan', 'Gluten-free'], '{}', '{"Fresh":47,"Great value":43,"Would order again":36,"Soupy":31,"Comforting":29}'::jsonb, false),
  (9, 5, 'Moules Mariniere', 13.90, 'A kilo of mussels in white wine, garlic and cream, with frites for the sauce.', 'mains', 1, '{}', array['Shellfish', 'Dairy'], '{"Fresh":39,"Comforting":31,"Great value":27,"Soupy":23}'::jsonb, false),
  (10, 5, 'Duck Confit', 18.50, 'Crisp-skinned duck leg with dauphinoise and a red wine jus.', 'mains', 2, array['Gluten-free'], '{}', '{"Rich":58,"Crispy":44,"Would order again":39}'::jsonb, false),
  (11, 6, 'Oxford Blue Bagel', 6.20, 'Toasted bagel with melted Oxford Blue cheese. A late-night institution.', 'mains', 1, array['Vegetarian'], array['Gluten', 'Dairy'], '{"Comforting":34,"Great value":28,"Rich":22,"Salty":18}'::jsonb, false),
  (12, 6, 'Cookie Dough Ice Cream', 4.50, 'Made in-house daily. The scoop that ends most Cowley Road evenings.', 'desserts', 1, array['Vegetarian'], array['Dairy', 'Egg', 'Gluten'], '{"Comforting":74,"Would order again":61,"Great value":48,"Sweet":45}'::jsonb, false),
  (13, 7, 'Khao Man Gai', 9.00, 'Poached chicken and ginger rice from the market stall with the longest Wednesday queue in Oxford.', 'mains', 1, array['Gluten-free'], array['Soy'], '{"Great value":118,"Would order again":102,"Comforting":71,"Soupy":54,"Fresh":42}'::jsonb, false),
  (14, 8, 'Chicken Katsu Curry', 12.50, 'Panko chicken, glossy house curry sauce, pickles and sticky rice.', 'mains', 1, '{}', array['Gluten', 'Egg', 'Soy'], '{"Crispy":66,"Comforting":52,"Generous portion":41,"Sweet":29}'::jsonb, false),
  (15, 9, 'Wild Mushroom Gnocchi', 15.00, 'Hand-rolled gnocchi with wild mushrooms, sage butter and parmesan.', 'mains', 1, array['Vegetarian'], array['Gluten', 'Dairy'], '{"Rich":29,"Comforting":24,"Fresh":15}'::jsonb, true)
on conflict (id) do update set
  restaurant_id = excluded.restaurant_id,
  name = excluded.name,
  price = excluded.price,
  description = excluded.description,
  course = excluded.course,
  menu_position = excluded.menu_position,
  diets = excluded.diets,
  allergens = excluded.allergens,
  crowd_tags = excluded.crowd_tags,
  sponsored = excluded.sponsored;

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'dishes' and column_name = 'restaurant'
  ) then
    execute $sync_legacy_columns$
      update public.dishes dish
      set restaurant = restaurant.name,
          area = restaurant.area,
          cuisine = restaurant.cuisine,
          tag_counts = dish.crowd_tags
      from public.restaurants restaurant
      where restaurant.id = dish.restaurant_id
    $sync_legacy_columns$;
  end if;
end $$;

alter table public.dishes alter column restaurant_id set not null;

create unique index if not exists dishes_restaurant_name_idx
  on public.dishes (restaurant_id, name);

select setval(pg_get_serial_sequence('public.restaurants', 'id'), (select max(id) from public.restaurants));
select setval(pg_get_serial_sequence('public.dishes', 'id'), (select max(id) from public.dishes));

insert into public.profiles (id, email)
values ('00000000-0000-4000-8000-000000000001', 'seed@plate.invalid')
on conflict (id) do nothing;

with seed_scores(dish_id, score, rating_count) as (
  values
    (1, 9.1::numeric, 214), (2, 8.6::numeric, 158), (3, 9.4::numeric, 187),
    (4, 8.9::numeric, 143), (5, 8.7::numeric, 129), (6, 8.8::numeric, 104),
    (7, 8.4::numeric, 96), (8, 8.2::numeric, 88), (9, 8.1::numeric, 74),
    (10, 8.5::numeric, 91), (11, 7.8::numeric, 67), (12, 8.3::numeric, 112),
    (13, 9.0::numeric, 176), (14, 8.6::numeric, 98), (15, 8.0::numeric, 52)
)
insert into public.ratings (user_id, dish_id, score, visited_at)
select
  '00000000-0000-4000-8000-000000000001'::uuid,
  seed_scores.dish_id,
  seed_scores.score,
  current_date - ((series.n - 1) % 365)
from seed_scores
cross join lateral generate_series(1, seed_scores.rating_count) as series(n)
where not exists (
  select 1
  from public.ratings existing
  where existing.user_id = '00000000-0000-4000-8000-000000000001'::uuid
    and existing.dish_id = seed_scores.dish_id
);

create or replace view public.dish_catalog
with (security_barrier = true, security_invoker = false)
as
select
  d.id,
  d.restaurant_id,
  d.name,
  d.price,
  d.description,
  d.course,
  d.menu_position,
  d.diets,
  d.allergens,
  d.sponsored,
  restaurant.name as restaurant_name,
  restaurant.area,
  restaurant.cuisine,
  coalesce(round(rating_stats.score::numeric, 1), 0)::double precision as score,
  coalesce(rating_stats.rating_count, 0)::bigint as rating_count,
  coalesce(tag_stats.tag_counts, '{}'::jsonb) as tag_counts,
  coalesce(tag_stats.search_tags, '{}'::text[]) as search_tags
from public.dishes d
join public.restaurants restaurant on restaurant.id = d.restaurant_id
left join lateral (
  select avg(r.score) as score, count(*) as rating_count
  from public.ratings r
  where r.dish_id = d.id
) rating_stats on true
left join lateral (
  select
    jsonb_object_agg(initcap(rollup.tag), rollup.total order by rollup.total desc) as tag_counts,
    array_agg(rollup.tag order by rollup.total desc) as search_tags
  from (
    select source.tag, sum(source.total)::bigint as total
    from (
      select lower(trim(crowd.key)) as tag, crowd.value::bigint as total
      from jsonb_each_text(d.crowd_tags) crowd
      union all
      select lower(trim(user_tag.tag)) as tag, count(*)::bigint as total
      from public.ratings user_rating
      cross join lateral unnest(user_rating.tags) as user_tag(tag)
      where user_rating.dish_id = d.id and trim(user_tag.tag) <> ''
      group by lower(trim(user_tag.tag))
    ) source
    group by source.tag
  ) rollup
) tag_stats on true;

create or replace view public.restaurant_catalog
with (security_barrier = true, security_invoker = false)
as
select
  restaurant.id,
  restaurant.name,
  restaurant.area,
  restaurant.cuisine,
  restaurant.latitude,
  restaurant.longitude,
  restaurant.description,
  coalesce(round(avg(rating.score)::numeric, 1), 0)::double precision as score,
  count(rating.id)::bigint as rating_count
from public.restaurants restaurant
left join public.dishes dish on dish.restaurant_id = restaurant.id
left join public.ratings rating on rating.dish_id = dish.id
group by restaurant.id;

alter table public.profiles enable row level security;
alter table public.restaurants enable row level security;
alter table public.dishes enable row level security;
alter table public.ratings enable row level security;
alter table public.rating_photos enable row level security;

drop policy if exists "Restaurants are public" on public.restaurants;
create policy "Restaurants are public" on public.restaurants for select using (true);

drop policy if exists "Dishes are public" on public.dishes;
create policy "Dishes are public" on public.dishes for select using (true);

drop policy if exists "Profiles are owner managed" on public.profiles;
create policy "Profiles are owner managed" on public.profiles
  for all to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

drop policy if exists "Ratings are owner managed" on public.ratings;
create policy "Ratings are owner managed" on public.ratings
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Rating photos are owner managed" on public.rating_photos;
create policy "Rating photos are owner managed" on public.rating_photos
  for all to authenticated
  using (auth.uid() = user_id)
  with check (
    auth.uid() = user_id
    and exists (
      select 1 from public.ratings rating
      where rating.id = rating_id and rating.user_id = auth.uid()
    )
  );

revoke all on public.profiles, public.ratings, public.rating_photos from anon;
grant select on public.restaurants, public.dishes, public.dish_catalog, public.restaurant_catalog to anon, authenticated;
grant select, insert, update, delete on public.profiles, public.ratings, public.rating_photos to authenticated;
grant usage, select on all sequences in schema public to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'meal-photos',
  'meal-photos',
  false,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Meal photos are owner readable" on storage.objects;
create policy "Meal photos are owner readable" on storage.objects
  for select to authenticated
  using (
    bucket_id = 'meal-photos'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "Meal photos are owner uploadable" on storage.objects;
create policy "Meal photos are owner uploadable" on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'meal-photos'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "Meal photos are owner deletable" on storage.objects;
create policy "Meal photos are owner deletable" on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'meal-photos'
    and (storage.foldername(name))[1] = auth.uid()::text
  );
