begin;

set local lock_timeout = '10s';
set local statement_timeout = '10min';

-- ===========================================================================
-- Editor approval system: only admin-approved emails may submit edits.
-- Admin identity is sashankuday@gmail.com, checked by email on profiles.
-- ===========================================================================

alter table public.profiles
  add column if not exists can_edit boolean not null default false;

update public.profiles set can_edit = true where email = 'sashankuday@gmail.com';

create or replace function public.is_plate_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid()) and email = 'sashankuday@gmail.com'
  );
$$;

revoke all on function public.is_plate_admin() from public, anon;
grant execute on function public.is_plate_admin() to authenticated;

create table if not exists public.edit_access_requests (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references public.profiles(id) on delete cascade,
  email       text not null,
  status      text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at  timestamptz not null default now(),
  decided_at  timestamptz,
  decided_by  uuid references public.profiles(id)
);

create unique index if not exists edit_access_requests_user_idx on public.edit_access_requests (user_id);

alter table public.edit_access_requests enable row level security;

drop policy if exists "Users see their own edit request" on public.edit_access_requests;
create policy "Users see their own edit request"
on public.edit_access_requests for select
to authenticated
using ((select auth.uid()) = user_id or public.is_plate_admin());

revoke all on public.edit_access_requests from anon;
grant select on public.edit_access_requests to authenticated;

create or replace function public.request_edit_access()
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  caller uuid := (select auth.uid());
  caller_email text;
  request_id bigint;
begin
  if caller is null then
    raise exception 'You must be signed in to request edit access.';
  end if;
  select email into caller_email from public.profiles where id = caller;

  insert into public.edit_access_requests (user_id, email, status, created_at)
  values (caller, caller_email, 'pending', now())
  on conflict (user_id) do update
    set status = 'pending', email = excluded.email, created_at = now(), decided_at = null, decided_by = null
    where public.edit_access_requests.status <> 'approved'
  returning id into request_id;

  return request_id;
end;
$$;

revoke all on function public.request_edit_access() from public, anon;
grant execute on function public.request_edit_access() to authenticated;

create or replace function public.approve_edit_access(target_email text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_plate_admin() then
    raise exception 'Only the admin can approve edit access.';
  end if;

  update public.profiles set can_edit = true where email = target_email;

  update public.edit_access_requests
    set status = 'approved', decided_at = now(), decided_by = (select auth.uid())
    where email = target_email;
end;
$$;

revoke all on function public.approve_edit_access(text) from public, anon;
grant execute on function public.approve_edit_access(text) to authenticated;

create or replace function public.reject_edit_access(target_email text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_plate_admin() then
    raise exception 'Only the admin can reject edit access.';
  end if;

  update public.profiles set can_edit = false where email = target_email;

  update public.edit_access_requests
    set status = 'rejected', decided_at = now(), decided_by = (select auth.uid())
    where email = target_email;
end;
$$;

revoke all on function public.reject_edit_access(text) from public, anon;
grant execute on function public.reject_edit_access(text) to authenticated;

-- Gate the existing community-correction RPC on can_edit.
create or replace function public.submit_dish_attribute_flag(
  target_dish_id bigint,
  target_attribute text,
  correction_action text,
  correction_value jsonb
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  caller uuid := (select auth.uid());
  flag_id bigint;
  new_diets text[];
  new_allergens text[];
  new_menu_tags text[];
  text_value text;
  numeric_value numeric;
begin
  if caller is null then
    raise exception 'You must be signed in to suggest a correction.';
  end if;

  if not exists (select 1 from public.profiles where id = caller and can_edit) then
    raise exception 'Edit access has not been approved for this account yet.';
  end if;

  if target_attribute not in ('diets', 'allergens', 'price', 'name', 'menu_tags') then
    raise exception 'Attribute % cannot be edited by the community.', target_attribute;
  end if;

  if correction_action not in ('add', 'remove', 'correct') then
    raise exception 'Unknown correction action %.', correction_action;
  end if;

  if not exists (select 1 from public.dishes where id = target_dish_id) then
    raise exception 'Unknown dish %.', target_dish_id;
  end if;

  if exists (
    select 1 from public.dish_attribute_flags flag
    where flag.user_id = caller
      and flag.dish_id = target_dish_id
      and flag.attribute = target_attribute
      and flag.created_at > now() - interval '24 hours'
  ) then
    raise exception 'You have already corrected this field recently. Try again later.';
  end if;

  if target_attribute = 'diets' then
    select dish.diets into new_diets from public.dishes dish where dish.id = target_dish_id;
    text_value := btrim(correction_value #>> '{}');
    if text_value is null or text_value = '' then
      raise exception 'A diet value is required.';
    end if;
    if correction_action = 'add' then
      if not (text_value = any(new_diets)) then
        new_diets := array_append(new_diets, text_value);
      end if;
    elsif correction_action = 'remove' then
      new_diets := array_remove(new_diets, text_value);
    else
      raise exception 'Diets support add/remove only.';
    end if;
    update public.dishes set diets = new_diets, updated_at = now() where id = target_dish_id;

  elsif target_attribute = 'allergens' then
    select dish.allergens into new_allergens from public.dishes dish where dish.id = target_dish_id;
    text_value := btrim(correction_value #>> '{}');
    if text_value is null or text_value = '' then
      raise exception 'An allergen value is required.';
    end if;
    if correction_action = 'add' then
      if not (text_value = any(new_allergens)) then
        new_allergens := array_append(new_allergens, text_value);
      end if;
    elsif correction_action = 'remove' then
      new_allergens := array_remove(new_allergens, text_value);
    else
      raise exception 'Allergens support add/remove only.';
    end if;
    update public.dishes
      set allergens = new_allergens, allergens_verified = false, updated_at = now()
      where id = target_dish_id;

  elsif target_attribute = 'price' then
    if correction_action <> 'correct' then
      raise exception 'Price supports the correct action only.';
    end if;
    numeric_value := (correction_value #>> '{}')::numeric;
    if numeric_value is null or numeric_value < 0 then
      raise exception 'Enter a valid price.';
    end if;
    update public.dishes set price = numeric_value, updated_at = now() where id = target_dish_id;

  elsif target_attribute = 'name' then
    if correction_action <> 'correct' then
      raise exception 'Name supports the correct action only.';
    end if;
    text_value := btrim(correction_value #>> '{}');
    if text_value is null or text_value = '' then
      raise exception 'A dish name is required.';
    end if;
    update public.dishes set name = text_value, updated_at = now() where id = target_dish_id;

  elsif target_attribute = 'menu_tags' then
    select dish.menu_tags into new_menu_tags from public.dishes dish where dish.id = target_dish_id;
    text_value := btrim(correction_value #>> '{}');
    if text_value is null or text_value = '' then
      raise exception 'A tag value is required.';
    end if;
    if correction_action = 'add' then
      if not (text_value = any(new_menu_tags)) then
        new_menu_tags := array_append(new_menu_tags, text_value);
      end if;
    elsif correction_action = 'remove' then
      new_menu_tags := array_remove(new_menu_tags, text_value);
    else
      raise exception 'Tags support add/remove only.';
    end if;
    update public.dishes set menu_tags = new_menu_tags, updated_at = now() where id = target_dish_id;
  end if;

  insert into public.dish_attribute_flags (dish_id, user_id, attribute, action, value, applied_at)
  values (target_dish_id, caller, target_attribute, correction_action, correction_value, now())
  returning id into flag_id;

  return flag_id;
end;
$$;

alter table public.dish_attribute_flags drop constraint if exists dish_attribute_flags_attribute_check;
alter table public.dish_attribute_flags add constraint dish_attribute_flags_attribute_check
  check (attribute in ('diets', 'allergens', 'price', 'name', 'menu_tags'));

revoke all on function public.submit_dish_attribute_flag(bigint, text, text, jsonb) from public, anon;
grant execute on function public.submit_dish_attribute_flag(bigint, text, text, jsonb) to authenticated;

notify pgrst, 'reload schema';

commit;
