begin;

set local lock_timeout = '10s';
set local statement_timeout = '10min';

-- ---------------------------------------------------------------------------
-- Blocked ingredients on the profile (per-user, hidden by default in search).
-- ---------------------------------------------------------------------------

alter table public.profiles
  add column if not exists blocked_ingredients text[] not null default '{}';

comment on column public.profiles.blocked_ingredients is
  'Diner-blocked ingredients; matching dishes are hidden from search by default.';

-- ---------------------------------------------------------------------------
-- Restaurant info editing (editor-gated, mirrors submit_dish_attribute_flag).
-- ---------------------------------------------------------------------------

create table if not exists public.restaurant_attribute_flags (
  id             bigint generated by default as identity primary key,
  restaurant_id  bigint not null references public.restaurants(id) on delete cascade,
  user_id        uuid not null references public.profiles(id) on delete cascade,
  attribute      text not null check (attribute in ('name', 'description', 'cuisine', 'area')),
  value          jsonb not null,
  applied_at     timestamptz,
  created_at     timestamptz not null default now()
);

create index if not exists restaurant_attribute_flags_restaurant_idx
  on public.restaurant_attribute_flags (restaurant_id, attribute);

alter table public.restaurant_attribute_flags enable row level security;

drop policy if exists "Restaurant attribute flags are public" on public.restaurant_attribute_flags;
create policy "Restaurant attribute flags are public"
on public.restaurant_attribute_flags for select
to anon, authenticated
using (true);

grant select on public.restaurant_attribute_flags to anon, authenticated;

create or replace function public.update_restaurant_info(
  target_restaurant_id bigint,
  target_attribute text,
  new_value text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  caller uuid := (select auth.uid());
  flag_id bigint;
  clean_value text;
begin
  if caller is null then
    raise exception 'You must be signed in to edit restaurant information.';
  end if;

  if not exists (select 1 from public.profiles where id = caller and can_edit) then
    raise exception 'Edit access has not been approved for this account yet.';
  end if;

  if target_attribute not in ('name', 'description', 'cuisine', 'area') then
    raise exception 'Attribute % cannot be edited.', target_attribute;
  end if;

  if not exists (select 1 from public.restaurants where id = target_restaurant_id) then
    raise exception 'Unknown restaurant %.', target_restaurant_id;
  end if;

  clean_value := btrim(new_value);
  if target_attribute in ('name', 'cuisine', 'area') and (clean_value is null or clean_value = '') then
    raise exception 'A value is required for %.', target_attribute;
  end if;

  if target_attribute = 'name' then
    update public.restaurants set name = clean_value, updated_at = now() where id = target_restaurant_id;
  elsif target_attribute = 'description' then
    update public.restaurants set description = clean_value, updated_at = now() where id = target_restaurant_id;
  elsif target_attribute = 'cuisine' then
    update public.restaurants set cuisine = clean_value, updated_at = now() where id = target_restaurant_id;
  elsif target_attribute = 'area' then
    update public.restaurants set area = clean_value, updated_at = now() where id = target_restaurant_id;
  end if;

  insert into public.restaurant_attribute_flags (restaurant_id, user_id, attribute, value, applied_at)
  values (target_restaurant_id, caller, target_attribute, to_jsonb(clean_value), now())
  returning id into flag_id;

  return flag_id;
end;
$$;

revoke all on function public.update_restaurant_info(bigint, text, text) from public, anon;
grant execute on function public.update_restaurant_info(bigint, text, text) to authenticated;

notify pgrst, 'reload schema';

commit;
