begin;

set local lock_timeout = '10s';
set local statement_timeout = '10min';

-- ===========================================================================
-- Phase 0 — Schema foundation for the feature roadmap.
--   0.1 visits table (a trip = one restaurant on one day; ratings link to it)
--   0.2 profiles.dietary_requirements
--   0.3 UGC correction tables + auto-apply security-definer entry point
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- 0.1 Visits
-- ---------------------------------------------------------------------------

create table if not exists public.visits (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null references public.profiles(id) on delete cascade,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  visited_at    date not null default current_date check (visited_at <= current_date),
  notes         text not null default '' check (char_length(notes) <= 2000),
  created_at    timestamptz not null default now()
);

create index if not exists visits_user_idx on public.visits (user_id, visited_at desc);
create index if not exists visits_restaurant_idx on public.visits (restaurant_id);

-- One rating can hang off one visit; nullable so "rate without a visit" still works.
alter table public.ratings
  add column if not exists visit_id bigint references public.visits(id) on delete set null;

create index if not exists ratings_visit_idx on public.ratings (visit_id);

-- Backfill: synthesise one visit per (user, restaurant, visited_at) group so
-- historical ratings are not orphaned, then point each rating at its visit.
insert into public.visits (user_id, restaurant_id, visited_at)
select distinct rating.user_id, dish.restaurant_id, rating.visited_at
from public.ratings rating
join public.dishes dish on dish.id = rating.dish_id
where rating.visit_id is null
on conflict do nothing;

update public.ratings rating
set visit_id = visit.id
from public.dishes dish
join public.visits visit
  on visit.restaurant_id = dish.restaurant_id
where dish.id = rating.dish_id
  and visit.user_id = rating.user_id
  and visit.visited_at = rating.visited_at
  and rating.visit_id is null;

alter table public.visits enable row level security;

drop policy if exists "Visits are owner managed" on public.visits;
create policy "Visits are owner managed"
on public.visits for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

revoke all on public.visits from anon;
grant select, insert, update, delete on public.visits to authenticated;

-- ---------------------------------------------------------------------------
-- 0.2 Dietary requirements on the profile
-- ---------------------------------------------------------------------------

alter table public.profiles
  add column if not exists dietary_requirements text[] not null default '{}';

comment on column public.profiles.dietary_requirements is
  'Diner-selected dietary preferences, drawn from the client-side DIETS constant.';

-- ---------------------------------------------------------------------------
-- 0.3 UGC correction log + auto-apply entry point
-- ---------------------------------------------------------------------------

create table if not exists public.dish_attribute_flags (
  id          bigint generated by default as identity primary key,
  dish_id     bigint not null references public.dishes(id) on delete cascade,
  user_id     uuid not null references public.profiles(id) on delete cascade,
  attribute   text not null check (attribute in ('diets', 'allergens', 'price', 'name')),
  action      text not null check (action in ('add', 'remove', 'correct')),
  value       jsonb not null,
  applied_at  timestamptz,
  created_at  timestamptz not null default now()
);

create index if not exists dish_attribute_flags_dish_idx
  on public.dish_attribute_flags (dish_id, attribute);
create index if not exists dish_attribute_flags_user_idx
  on public.dish_attribute_flags (user_id, dish_id, attribute, created_at desc);

alter table public.dish_attribute_flags enable row level security;

-- The audit trail is world-readable (drives the "edited by the community"
-- provenance marker). Writes only ever happen through the definer function
-- below, so no insert/update/delete policy is granted to client roles.
drop policy if exists "Dish attribute flags are public" on public.dish_attribute_flags;
create policy "Dish attribute flags are public"
on public.dish_attribute_flags for select
to anon, authenticated
using (true);

grant select on public.dish_attribute_flags to anon, authenticated;

-- Aggregate provenance view: how many community edits each field has seen.
drop view if exists public.dish_attribute_flag_counts;
create view public.dish_attribute_flag_counts
with (security_barrier = true, security_invoker = true)
as
select
  flag.dish_id,
  flag.attribute,
  count(*)::bigint as flag_count,
  max(flag.created_at) as last_edited_at
from public.dish_attribute_flags flag
where flag.applied_at is not null
group by flag.dish_id, flag.attribute;

grant select on public.dish_attribute_flag_counts to anon, authenticated;

-- Auto-apply: submitting a correction is also the edit. A security-definer
-- function is the only writer of dishes.diets/allergens/price/name via this
-- path, so exactly which columns are diner-writable is controlled here.
-- Rate limit: one correction per user per dish per attribute per 24h.
create or replace function public.submit_dish_attribute_flag(
  target_dish_id bigint,
  target_attribute text,
  correction_action text,
  correction_value jsonb
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  caller uuid := (select auth.uid());
  flag_id bigint;
  new_diets text[];
  new_allergens text[];
  text_value text;
  numeric_value numeric;
begin
  if caller is null then
    raise exception 'You must be signed in to suggest a correction.';
  end if;

  if target_attribute not in ('diets', 'allergens', 'price', 'name') then
    raise exception 'Attribute % cannot be edited by the community.', target_attribute;
  end if;

  if correction_action not in ('add', 'remove', 'correct') then
    raise exception 'Unknown correction action %.', correction_action;
  end if;

  if not exists (select 1 from public.dishes where id = target_dish_id) then
    raise exception 'Unknown dish %.', target_dish_id;
  end if;

  -- Rate limit (a DB check, not client-side).
  if exists (
    select 1 from public.dish_attribute_flags flag
    where flag.user_id = caller
      and flag.dish_id = target_dish_id
      and flag.attribute = target_attribute
      and flag.created_at > now() - interval '24 hours'
  ) then
    raise exception 'You have already corrected this field recently. Try again later.';
  end if;

  if target_attribute = 'diets' then
    select dish.diets into new_diets from public.dishes dish where dish.id = target_dish_id;
    text_value := btrim(correction_value #>> '{}');
    if text_value is null or text_value = '' then
      raise exception 'A diet value is required.';
    end if;
    if correction_action = 'add' then
      if not (text_value = any(new_diets)) then
        new_diets := array_append(new_diets, text_value);
      end if;
    elsif correction_action = 'remove' then
      new_diets := array_remove(new_diets, text_value);
    else
      raise exception 'Diets support add/remove only.';
    end if;
    update public.dishes set diets = new_diets, updated_at = now() where id = target_dish_id;

  elsif target_attribute = 'allergens' then
    select dish.allergens into new_allergens from public.dishes dish where dish.id = target_dish_id;
    text_value := btrim(correction_value #>> '{}');
    if text_value is null or text_value = '' then
      raise exception 'An allergen value is required.';
    end if;
    if correction_action = 'add' then
      if not (text_value = any(new_allergens)) then
        new_allergens := array_append(new_allergens, text_value);
      end if;
    elsif correction_action = 'remove' then
      new_allergens := array_remove(new_allergens, text_value);
    else
      raise exception 'Allergens support add/remove only.';
    end if;
    -- A non-owner correction invalidates the restaurant verification badge.
    update public.dishes
      set allergens = new_allergens, allergens_verified = false, updated_at = now()
      where id = target_dish_id;

  elsif target_attribute = 'price' then
    if correction_action <> 'correct' then
      raise exception 'Price supports the correct action only.';
    end if;
    numeric_value := (correction_value #>> '{}')::numeric;
    if numeric_value is null or numeric_value < 0 then
      raise exception 'Enter a valid price.';
    end if;
    update public.dishes set price = numeric_value, updated_at = now() where id = target_dish_id;

  elsif target_attribute = 'name' then
    if correction_action <> 'correct' then
      raise exception 'Name supports the correct action only.';
    end if;
    text_value := btrim(correction_value #>> '{}');
    if text_value is null or text_value = '' then
      raise exception 'A dish name is required.';
    end if;
    update public.dishes set name = text_value, updated_at = now() where id = target_dish_id;
  end if;

  insert into public.dish_attribute_flags (dish_id, user_id, attribute, action, value, applied_at)
  values (target_dish_id, caller, target_attribute, correction_action, correction_value, now())
  returning id into flag_id;

  return flag_id;
end;
$$;

revoke all on function public.submit_dish_attribute_flag(bigint, text, text, jsonb) from public, anon;
grant execute on function public.submit_dish_attribute_flag(bigint, text, text, jsonb) to authenticated;

notify pgrst, 'reload schema';

commit;
