ALTER TABLE public.dishes
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(
  pg_get_serial_sequence('public.dishes', 'id'),
  COALESCE((SELECT MAX(id) FROM public.dishes), 0) + 1,
  false
);
